name: 'Cloudformation'

on:
  workflow_dispatch:
    inputs:
      account_id:
        description: "Enter the Target Account ID. For multiple targets add account Id's with space"
        required: true
        default: ""
      region:
        type: choice
        description: "Select the Target Account region"
        required: true
        options:
          - eu-central-1 
          - us-east-1
          
          
permissions:
  contents: read

jobs:
  build:
    name:  ${{matrix.runner}} - ${{ matrix.environment }}
    runs-on: [ '${{ matrix.runner }}']
    strategy:
      max-parallel: 1
      matrix:
         include:
           - environment: test
             runner: ubuntu-latest
           
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: eu-central-1

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install troposphere Dependencies
      id: install_troposphere
      run: |
        pip install troposphere
        
    - name: Build CF template
      id: create_CF_template
      run: |
        python3 build-cloudformation-vpc.py > cloudformation.json
        
    - name: Validate CF template
      id: validate_CF_template
      run: |
        aws cloudformation validate-template --template-body file://cloudformation.json
        echo "{{ github.event.inputs.account_id }}" >> account.txt
        
    - name: my-artifact
      uses: actions/upload-artifact@v3
      with:
        path: account.txt
        
