name: 'Cloudformation'

on:
  workflow_dispatch:
    inputs:
      region:
        type: choice
        description: "Select the region"
        required: true
        options:
          - eu-central-1 
          - us-east-1 
          
permissions:
  contents: read

jobs:
  build:
    name:  ${{matrix.runner}} - ${{ matrix.environment }}
    runs-on: [ '${{ matrix.runner }}']
    strategy:
      max-parallel: 1
      matrix:
         include:
           - environment: test
             runner: ubuntu-latest
           
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: ${{ github.event.inputs.region }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install troposphere Dependencies
      id: install_troposphere
      run: |
        pip install troposphere
        
    - name: Build CF template
      id: create_CF_template
      run: |
        python3 build-cloudformation-vpc-2.py > cloudformation.json
        
    - name: deploy CF template
      id: deploy_CF_template
      run: |
        aws cloudformation deploy \
        --no-fail-on-empty-changeset \
        --template-file cloudformation.json \
        --stack-name "AnkitaTest"
